### ISSUE TITLE
Compatibility with WooCommerce Product Add-ons

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#113]
The client is having an issue when WooCommerce product add-ons plugin is used to add the extra fields. 
Suppose 2 add-ons have been selected. So, on the order page, it shows both the add-ons while on the invoice page, it shows only one add-on.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/10921

**Comment by kenil802** [comment]
Another client has the same issue

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/19721

**Comment by kenil802** [comment]
The client is having an issue when the File Upload product add-on is set for the product. After uploading the file on the product page, it shows only the file name and extension. But after placing an order, and clicking on the invoice, it shows the whole path instead of the file name and extension.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/22962

**Comment by kenil802** [comment]
One more client has reported the same issue where all the add-ons are not getting printed in the invoice.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25984

**Comment by Shasvat7** [comment]
The issue where the addons are not coming in the invoices is not been replicated with the latest version, here are the screenshots:
https://prnt.sc/22k97o7
https://prnt.sc/22k76bz
https://prnt.sc/22k7g6y
https://prnt.sc/22k7orx

the issue coming is about the file value, where whole URL path is coming instead of the filename so will fix that issue.
