### ISSUE TITLE
Quantity column shows incorrect in the print invoice when working with WC Composite products  

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce#150]
The issue is when we work with the Composite products, the quantity column in the print invoice is showing incorrect.

Steps to reproduce:
1) Create a composite product
2) Add 3 components or child products to it.
3) Place an order
4) print the invoice for that order and you will see 4 in the quantity column. This means the Original Composite product is also being added to the count.

However, the quantity should be 3 i.e the count of only the child products. The same issue is being faced when we work with the WC Product Bundle plugin.

Link: https://wordpress.org/support/topic/wrong-total-quantity-due-to-composite-bundle/#post-13542652

**Comment by apeksha10** [comment]
Hi all,

Now Invoice shows Total 0 instead of 3 and even some deprecated notice also appear 

please refer to the below screenshot 
 Order placed screenshot: https://www.screencast.com/t/p0mJg1hIZ2
Total Qty shows "0" screenshot: https://www.screencast.com/t/Lg4AnDJPP7E
Deprecated Notice screenshot : https://www.screencast.com/t/anIlYjtb4


Hence I have re-open this issue

**Comment by apeksha10** [comment]
After taking the latest copy, Now Invoice qty shows Total 3  (woo-order page clicked on Print Invoice button)

But my concern is when I placed an order and clicked on the "Print" button on the order received page I got the "Oops! That page can’t be found" message.
